apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdf-service
spec: 
  template:
    spec:
      containers:
      - name: name
        image: ghcr.io/jodevsa/paperwork/pdf-service:main
        imagePullPolicy: Always