apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  template:
    spec:
      containers:
      - name: name
        image: ghcr.io/jodevsa/paperwork/user-service:main
        imagePullPolicy: Always