apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
spec:
  template:
    spec:
      containers:
      - name: name
        image: ghcr.io/jodevsa/paperwork/ui:main
        imagePullPolicy: Always