apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pdfmaker-dev
bases:
- ../base


resources:
- mongodb.deployment.yaml
- mongodb.svc.yaml

patchesStrategicMerge:
- image.pdfmaker.deployment.yaml
- env.pdfmaker.deployment.yaml
- image.config-service.deployment.yaml
- env.config-service.deployment.yaml
- image.user-service.deployment.yaml
- env.user-service.deployment.yaml
- image.ui.deployment.yaml


patchesJson6902:
- target:
    group: extensions
    version: v1beta1
    kind: Ingress
    name: micro-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: dev.pdfmaker.local
    - op: replace
      path: /spec/tls/0/hosts/0
      value: dev.pdfmaker.local