name: build and push docker images

on:
  push:
    branches: ['main']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2


      -  run: ./deploy.sh

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}




      # build pdfmaker image




      - name: Extract metadata (tags, labels) for Dockerfile.pdfmaker
        id: pdfmaker
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/pdfmaker

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: Dockerfile.pdfmaker
          tags: ${{ steps.pdfmaker.outputs.tags }}
          push: true
          labels: ${{ steps.pdfmaker.outputs.labels }}





      # build ui image




      - name: Extract metadata (tags, labels) for Dockerfile.ui
        id: ui
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/ui

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: Dockerfile.ui
          tags: ${{ steps.ui.outputs.tags }}
          push: true
          labels: ${{ steps.ui.outputs.labels }}



      # build config service image



      - name: Extract metadata (tags, labels) for Dockerfile.config-service
        id: configservice
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/configservice

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: Dockerfile.config-service
          tags: ${{ steps.configservice.outputs.tags }}
          push: true
          labels: ${{ steps.configservice.outputs.labels }}
